### Send us a message
POST http://localhost:8086/contact-us
content-type: application/json

{
    "name": "Victor",
    "email": "victor@kippa.africa",
    "message": "Hey bitches, I'm the fucking admin here everybody else shut the fuck up!"
}



### Get all messages
GET http://localhost:8086/contact-us/all-messages



### Reply a message, technically
POST http://localhost:8086/contact-us/reply-message/3
content-type: application/json

{
    "replied": true
}



### Get all replied messages
GET http://localhost:8086/contact-us/replied-messages

