### Create a new user
POST http://localhost:8086/auth/signup
content-type: application/json

{
    "email": "jephtah@kippa.africa",
    "username": "Jeph",
    "password": "password"
}


### Signin an existing user
POST http://localhost:8086/auth/signin
content-type: application/json

{
    "email": "victor@kippa.africa",
    "password": "password"
}


### Signout the currently signed in user
POST http://localhost:8086/auth/signout



### Find a particular user with ID   
GET http://localhost:8086/auth/be7c92b2-a409-428e-a0d9-4f1232aa3844



### Find all users registered with a given email
GET http://localhost:8086/auth?email=midas@kippa.africa



### Delete a user with a given ID
DELETE http://localhost:8086/auth?id=032688c9-424f-46c4-8de3-cd664e36b3d6



### Update a user with a given ID
PATCH http://localhost:8086/auth/1c2f8f3b-aa08-41ff-81e7-4057fe76abc5
content-type: application/json

{
    "username": "Victor",
    "admin": true
}



### Get the currently signed in user
GET http://localhost:8086/auth/whoami



### Get all registered emails - refactored
GET http://localhost:8086/auth/emails?page=1&take=3