#### PRODUCT ROUTES ###

### Create A Product
POST http://localhost:8086/product/create-product
content-type: application/json

{
    "name": "Wristband",
    "description": "Black Medium Wristband",
    "price": 15.00,
    "discount": 10.00,
    "quantity_in_stock": 2
}


### Preview A Product
GET http://localhost:8086/product/preview-product/c1863e0b-cb49-4e5d-9cdb-c6d72e1adf2e


### Get All Products
GET http://localhost:8086/product/products?page=1&take=4


### Update A Product
PATCH http://localhost:8086/product/update-product/?product_id=d575b5a5-6440-48ed-8db2-8ba4fb7c254b
content-type: application/json

{
    "is_in_stock": true
}


### Delete A Product
DELETE http://localhost:8086/product/remove-product?product_id=90d084c2-70e1-43d3-821c-c85b54389ac2






### CART ROUTES ###

### Adds A Product To A Cart As A Cart_Item
POST http://localhost:8086/cart/add-to-cart/3fda9b6c-9054-490f-8df5-be3a8c958bca
content-type: application/json

### Removes An Item from A Cart
PATCH http://localhost:8086/cart/remove-from-cart?product_id=3fda9b6c-9054-490f-8df5-be3a8c958bca
