### Create a new user
POST http://localhost:5000/auth/signup
content-type: application/json

{
    "email": "piper@kippa.com",
    "password": "piper"
}



### Signin an existing user
POST http://localhost:5000/auth/signin
content-type: application/json

{
    "email": "victor@kippa.africa",
    "password": "killshot"
}



### Signout the currently signed in user
POST http://localhost:5000/auth/signout



### Find a particular user with ID   
GET http://localhost:5000/auth/2



### Find all users registered with a given email
GET http://localhost:5000/auth?email=hello@kippa.africa



### Delete a user with a given ID
DELETE http://localhost:5000/auth/2



### Update a user with a given ID
PATCH http://localhost:5000/auth/6
content-type: application/json

{
    "email": "mercy@kippa.africa",
    "admin": true
}



### Get the currently signed in user
GET http://localhost:5000/auth/whoami