### Create a new blogpost
POST http://localhost:8086/blogposts
content-type: application/json

{
    "title": "The Essence Of Humanity",
    "description": "An expository on the purpose of human existence",
    "content": "Sometimes we have to take a step back and contemplate the essence of our existence..."
}


### Get a particular blogpost based on ID
GET http://localhost:8086/blogposts/02e0046f-85e8-41ad-ad1c-8095559e3f9b


### Approve a particular post based on ID
PATCH http://localhost:8086/blogposts/approve/02e0046f-85e8-41ad-ad1c-8095559e3f9b
content-type: application/json

{
    "approved": true
}   

### Get all posts
GET http://localhost:8086/blogposts

### Get all posts
GET http://localhost:8086/blogposts/paginated?page=1&take=2


### Get all approved posts
GET http://localhost:8086/blogposts/passers