### Create a new blogpost
POST http://localhost:8086/blogposts
content-type: application/json

{
    "title": "The Essence Of Humanity",
    "description": "An expository on the purpose of human existence",
    "content": "Sometimes we have to take a step back and contemplate the essence of our existence..."
}


### Get a particular blogpost based on ID
GET http://localhost:8086/blogposts/6


### Approve a particular post based on ID
PATCH http://localhost:8086/blogposts/approve/3
content-type: application/json

{
    "approved": true
}   

### Get all posts
GET http://localhost:8086/blogposts


### Get all approved posts
GET http://localhost:8086/blogposts/passers